'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "users",
      [
        {
          username: "admin_cpic",
          email: "admin@cpic.edu.co",
          password: "hashed_password",
          phone: "3100000001",
          birthdate: "1985-05-12",
          document: 100000001,
          gender: "M",
          state: true,
          rolId: 1,
          passwordResetToken: null,
          passwordResetExpires: null,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          username: "coordinador1",
          email: "coordinador1@cpic.edu.co",
          password: "hashed_password",
          phone: "3100000002",
          birthdate: "1980-08-20",
          document: 100000002,
          gender: "F",
          state: true,
          rolId: 2,
          passwordResetToken: null,
          passwordResetExpires: null,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          username: "bienestar1",
          email: "bienestar1@cpic.edu.co",
          password: "hashed_password",
          phone: "3100000003",
          birthdate: "1990-03-14",
          document: 100000003,
          gender: "M",
          state: true,
          rolId: 3,
          passwordResetToken: null,
          passwordResetExpires: null,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          username: "instructor1",
          email: "instructor1@cpic.edu.co",
          password: "hashed_password",
          phone: "3100000004",
          birthdate: "1987-01-25",
          document: 100000004,
          gender: "F",
          state: true,
          rolId: 4,
          passwordResetToken: null,
          passwordResetExpires: null,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          username: "aprendiz1",
          email: "aprendiz1@cpic.edu.co",
          password: "hashed_password",
          phone: "3100000005",
          birthdate: "2002-07-10",
          document: 100000005,
          gender: "M",
          state: true,
          rolId: 5,
          passwordResetToken: null,
          passwordResetExpires: null,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          username: "aprendiz2",
          email: "aprendiz2@cpic.edu.co",
          password: "hashed_password",
          phone: "3100000006",
          birthdate: "2001-09-18",
          document: 100000006,
          gender: "F",
          state: true,
          rolId: 5,
          passwordResetToken: null,
          passwordResetExpires: null,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          username: "aprendiz3",
          email: "aprendiz3@cpic.edu.co",
          password: "hashed_password",
          phone: "3100000007",
          birthdate: "2000-04-02",
          document: 100000007,
          gender: "M",
          state: true,
          rolId: 5,
          passwordResetToken: null,
          passwordResetExpires: null,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          username: "aprendiz4",
          email: "aprendiz4@cpic.edu.co",
          password: "hashed_password",
          phone: "3100000008",
          birthdate: "2003-11-21",
          document: 100000008,
          gender: "F",
          state: true,
          rolId: 5,
          passwordResetToken: null,
          passwordResetExpires: null,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          username: "instructor2",
          email: "instructor2@cpic.edu.co",
          password: "hashed_password",
          phone: "3100000009",
          birthdate: "1983-02-28",
          document: 100000009,
          gender: "M",
          state: true,
          rolId: 4,
          passwordResetToken: null,
          passwordResetExpires: null,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          username: "instructor3",
          email: "instructor3@cpic.edu.co",
          password: "hashed_password",
          phone: "3100000010",
          birthdate: "1989-06-15",
          document: 100000010,
          gender: "F",
          state: true,
          rolId: 4,
          passwordResetToken: null,
          passwordResetExpires: null,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          username: "bienestar2",
          email: "bienestar2@cpic.edu.co",
          password: "hashed_password",
          phone: "3100000011",
          birthdate: "1991-10-08",
          document: 100000011,
          gender: "F",
          state: true,
          rolId: 3,
          passwordResetToken: null,
          passwordResetExpires: null,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          username: "bienestar3",
          email: "bienestar3@cpic.edu.co",
          password: "hashed_password",
          phone: "3100000012",
          birthdate: "1992-12-12",
          document: 100000012,
          gender: "M",
          state: true,
          rolId: 3,
          passwordResetToken: null,
          passwordResetExpires: null,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          username: "coordinador2",
          email: "coordinador2@cpic.edu.co",
          password: "hashed_password",
          phone: "3100000013",
          birthdate: "1981-07-30",
          document: 100000013,
          gender: "M",
          state: true,
          rolId: 2,
          passwordResetToken: null,
          passwordResetExpires: null,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          username: "coordinador3",
          email: "coordinador3@cpic.edu.co",
          password: "hashed_password",
          phone: "3100000014",
          birthdate: "1979-03-09",
          document: 100000014,
          gender: "F",
          state: true,
          rolId: 2,
          passwordResetToken: null,
          passwordResetExpires: null,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          username: "aprendiz5",
          email: "aprendiz5@cpic.edu.co",
          password: "hashed_password",
          phone: "3100000015",
          birthdate: "2004-01-13",
          document: 100000015,
          gender: "M",
          state: true,
          rolId: 5,
          passwordResetToken: null,
          passwordResetExpires: null,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          username: "aprendiz6",
          email: "aprendiz6@cpic.edu.co",
          password: "hashed_password",
          phone: "3100000016",
          birthdate: "2002-05-23",
          document: 100000016,
          gender: "F",
          state: true,
          rolId: 5,
          passwordResetToken: null,
          passwordResetExpires: null,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          username: "aprendiz7",
          email: "aprendiz7@cpic.edu.co",
          password: "hashed_password",
          phone: "3100000017",
          birthdate: "2003-09-05",
          document: 100000017,
          gender: "M",
          state: true,
          rolId: 5,
          passwordResetToken: null,
          passwordResetExpires: null,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          username: "aprendiz8",
          email: "aprendiz8@cpic.edu.co",
          password: "hashed_password",
          phone: "3100000018",
          birthdate: "2001-11-19",
          document: 100000018,
          gender: "F",
          state: true,
          rolId: 5,
          passwordResetToken: null,
          passwordResetExpires: null,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          username: "aprendiz9",
          email: "aprendiz9@cpic.edu.co",
          password: "hashed_password",
          phone: "3100000019",
          birthdate: "2000-02-11",
          document: 100000019,
          gender: "M",
          state: true,
          rolId: 5,
          passwordResetToken: null,
          passwordResetExpires: null,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          username: "aprendiz10",
          email: "aprendiz10@cpic.edu.co",
          password: "hashed_password",
          phone: "3100000020",
          birthdate: "2002-06-29",
          document: 100000020,
          gender: "F",
          state: true,
          rolId: 5,
          passwordResetToken: null,
          passwordResetExpires: null,
          createdAt: new Date(),
          updatedAt: new Date()
        }
      ],
      {}
    ) 
  },

  async down (queryInterface, Sequelize) {
    await queryInterface.bulkDelete('users', null, {})
  }
};
